### ISSUE TITLE
I can create Instance, list istance, read qrcode, but I have error on sent message or file to 

### ISSUE THREAD

**Issue by enricogaggero** [paulojuniorbls/euAtendoWhatsDelphi#4]
Hi, I don't know if it's a problem of incorrect configuration of evolution-api but when I try to send a message or file I receive an error: Invalid JSON response.
However, there are no problems creating an Instance, scanning the QR code, listing the instances, listing the contact list.
Have you planned the possibility of creating a property to activate and where to save in a log file the errors received from the server?
I think my problem is due to the fact that I'm sending messages to the Italy region (I'm Italian) and I don't know how to configure the CodigoPais and DDDPadrao. Do you have any advice on this?
A thousand thanks

**Comment by paulojuniorbls** [comment]
You are using v1 or v2 of the API, regarding the DDD configuration, comment on the number formatting function, so you can resolve to use in your country.
